#
# configuration for meson-corpus-test-update
#
# This file provides extra information for the list of projects taken from
# Users.md
#
# project names are converted to putative package names by lowercasing, and
# replacing spaces with dashes
#
# blacklisted:          if present, project will not be built
# builddep:             override the package name to 'apt-get builddep', or should be false to skip if the project isn't packaged for Ubuntu
# install:              list of additional packages to 'apt-get install'
# repo-url:             git repo URL, if different to that linked in Users.md
# commit:               git branch, tag, or commit-id, otherwise master is used
# extra-commands:       extra commands to execute before build
# sourcedir:            source directory containing meson.build, if not root of checkout
# config:               project configuration options to be passed to meson
# build:                targets to build (default: all install), or false to skip
#

arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

bolt:
  builddep: false
  install:
  - libglib2.0-dev
  - libudev-dev
  - udev
  - libpolkit-gobject-1-dev
  - systemd
  - libsystemd-dev

budgie-desktop:
  builddep: false
  install:
  - valac
  - libgtk-3-dev
  - libwnck-3-dev
  - libpeas-dev
  - uuid-dev
  - libibus-1.0-dev
  - libgnome-desktop-3-dev
  - libaccountsservice-dev
  - intltool
  - libpulse-dev
  - sassc
  - libpolkit-agent-1-dev
  - libmutter-2-dev
  - libgnome-menu-3-dev
  - libupower-glib-dev
  - libgnome-bluetooth-dev
  - gtk-doc-tools
  - gnome-settings-daemon-dev
  build: false

casync:
  install:
  - libudev-dev

dbus-broker:
  builddep: false
  install:
  - python-docutils
  - libdbus-1-dev
  - libglib2.0-dev
  - libsystemd-dev
  - systemd

dpdk:
  builddep: false
  repo-url: git://dpdk.org/dpdk
  build: false

dxvk:
  blacklisted: 'need to work out how to install vulcan devkit'

emeus:
  builddep: false
  install:
  - libglib2.0-dev
  - libgtk-3-dev
  - libgirepository1.0-dev
  build: false

esp8266-arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

fedora-project:
  blacklisted: 'not a package'

fractal:
  builddep: false
  repo-url: https://gitlab.gnome.org/World/fractal.git
  install:
  - cargo
  - gettext
  - libatk1.0-dev
  - libcariro2-dev
  - libdbus-1-dev
  - libgdk-pixbuf2.0-dev
  - libgspell-1-dev
  - libgtk-3-dev
  - libpango1.0-dev
  - libssl-dev
  - rustc
  blacklisted: 'requires gspell >= 1.8; just wraps cargo-build'

frida:
  blacklisted: 'repo-url is for frida-core, make a meson.build of frida using subprojects'

fwupd:
  install:
  - gnu-efi
  - libjson-glib-dev
  - help2man
  - valac
  # pin at a working commit before efiboot required, not packaged in bionic
  commit: cff980cfda882939b5a3a5c2baadb657d5dbb051

geary:
  install:
  - libunwind-dev
  - libgoa-1.0-dev
  - itstool
  - libjson-glib-dev
  repo-url: https://git.gnome.org/browse/geary

glib:
  builddep: glib2.0
  build: false

gnome-boxes:
  install:
  - libwebkit2gtk-4.0-dev
  - freerdp2-dev

gnome-builder:
  # pin before libdazzle >= 3.29 required, not in bionic
  commit: 3.28.3
  # spellcheck uses enchant2, not in bionic
  config: -Dwith_spellcheck=false
  build: false

gnome-recipes:
  install:
  - libgoa-1.0-dev
  - libjson-glib-dev

gnome-software:
  # pin before flatpak >= 0.99.3 required, not in bionic
  commit: 12031b42109892e50b38f4037b923335fdfb0fd0

gnome-twitch:
  build: false

gnome-usage:
  builddep: false
  install:
  - libaccountsservice-dev
  - libgtk-3-dev
  - libgtop2-dev
  - valac

graphene:
  repo-url: git://github.com/ebassi/graphene

grilo:

grilo-plugins:
  # pin at commit before grilo >= 0.3.6 required, not in bionic
  commit: 770b11088c1b99ec979015faf95078c1e0dfe69e

gstreamer:
  builddep: gstreamer1.0
  # install fails in non-UTF8 locale due to encoding issue in gtkdochelper.py
  build: all

gtk+:
  builddep: libgtk-3-dev
  # pin at commit before pango >= 1.14.0 required, not in bionic
  commit: 894a0c0f
  build: false

gtkdapp:
  builddep: false
  install:
  - libgtkd-3-dev
  - gdc
  - gsettings-desktop-schemas-dev
  - libglib2.0-dev
  - gettext
  build: false

gvfs:
  install:
  - libbluray-dev
  - libnfs-dev
  # pin at commit before polkit-gobject-1 >= 0.114 required, not in bionic
  commit: 3a7bb06be72fc62b4ec524afe67febf0f529066d

hardcode-tray:
  builddep: false
  install:
  - libgirepository1.0-dev
  - libgtk-3-dev

hexchat:
  install:
  - libluajit-5.1-dev

igt:
  builddep: intel-gpu-tools
  install:
  - libssl-dev
  - libdw-dev

jsoncpp:
  builddep: false

kiwix-libraries:
  builddep: false
  install:
  - libicu-dev
  - libzim-dev
  blacklisted: 'needs libzim >= 4.0.0, not in bionic'

libdrm:

libepoxy:
  build: false

libfuse:
  install:
  - udev
  builddep: fuse

libgit2-glib:
  install:
  - python-gi-dev

libhttpseverywhere:
  builddep: false
  install:
  - valac
  - libjson-glib-dev
  - libsoup2.4-dev
  - libgee-0.8-dev
  - libarchive-dev
  - gobject-introspection
  build: false

libmodulemd:
  builddep: false
  install:
  - clang-format
  - gobject-introspection
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libyaml-dev
  - python-autopep8
  - valgrind

libosmscout:
  builddep: false

libspng:
  builddep: false
  install:
  - zlib1g-dev
  - libpng-dev

libzim:
  builddep: zimlib

lightdm-webkit2-greeter:
  builddep: false
  commit: stable
  install:
  - libdbus-glib-1-dev
  - liblightdm-gobject-1-dev
  - libgtk-3-dev
  - libwebkit2gtk-4.0-dev
  repo-url: https://github.com/Antergos/lightdm-webkit2-greeter

mesa:
  install:
  - libegl1-mesa-dev
  - libxvmc-dev
  # pin at commit before wayland needs to provide wayland-egl-backend (>= 1.15?), not in bionic
  commit: cb03803253b026d5f4c1e0fef431a12df461e6d8
  build: false

miraclecast:
  builddep: false
  install:
  - libudev-dev
  - libglib2.0-dev
  - libsystemd-dev
  build: false

nautilus:
  install:
  - libgexiv2-dev
  - libseccomp-dev
  repo-url: https://gitlab.gnome.org/GNOME/nautilus.git

nemo:
  install:
  - libxapp-dev

orc:

outlier:
  builddep: false

pango:
  install:
  - libfribidi-dev
  builddep: pango1.0

parzip:
  builddep: false
  extra-commands: meson wrap update zlib

pipewire:
  builddep: false
  install:
  - libdbus-1-dev
  - libasound2-dev
  - libv4l-dev
  - libudev-dev
  repo-url: https://github.com/PipeWire/pipewire.git

pithos:
  install:
  - libglib2.0-dev

pitivi:
  blacklisted: 'has unpackaged subproject gst-transcoder, which depends on gstreamer-1.0 > 1.15.0, not in bionic'

polari:
  # pin at commit before gjs-1.0 1.53.90 required, not in bionic
  commit: c97477b23361855e22619546a297d7513163bb76

radare2:
  # yes, I threw up in my mouth, a bit...
  extra-commands: (cd shlr; ./capstone.sh https://github.com/aquynh/capstone.git next)

sshfs:
  # pin at commit before libfuse3 required, not in bionic
  commit: 6cc86fc0bdaaeacfb1bd5e4336f2a2d1e5b189b8

sysprof:
  install:
  - systemd

szl:
  builddep: false
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init

taisei-project:
  builddep: false
  install:
  - libfreetype6-dev
  - libsdl2-dev
  - libsdl2-image-dev
  - libpng-dev
  - python-docutils
  repo-url: https://github.com/taisei-project/taisei.git

valum:
  builddep: false
  install:
  - valac
  - libsoup2.4-dev
  - libssl-dev

wayland-and-weston:
  builddep: false
  install:
  - libudev-dev
  - libmtdev-dev
  - libevdev-dev
  - libwacom-dev
  - doxygen
  - graphviz
  - libgtk-3-dev
  - check
  - valgrind
  - python-sphinx
  - python-sphinx-rtd-theme
  - python-recommonmark
  repo-url: git://anongit.freedesktop.org/wayland/libinput

wlroots:
  builddep: false
  install:
  - libegl1-mesa-dev
  - libgbm-dev
  - libgles2-mesa-dev
  - libinput-dev
  - libpixman-1-dev
  - libwayland-dev
  - libxcb-composite0-dev
  - libxcb-image0-dev
  - libxkbcommon-dev
  - wayland-protocols
  # pin at commit before wayland-protocols >= 1.14 required, not in bionic
  commit: f1fcc685b62d5c37c3b99ce6bfeb11ac1fa59ea6

xi-gtk:
  builddep: false
  install:
  - valac
  - libgtk-3-dev
  - libjson-glib-dev

xorg:
  builddep: xorg-server

zstandard:
  builddep: zstd
  repo-url: https://github.com/facebook/zstd.git
  sourcedir: contrib/meson
  commit: v1.3.4
