#
# configuration for meson-corpus-test-update
#
# This file provides extra information for the list of projects taken from
# Users.md
#
# project names are converted to putative package names by lowercasing, and
# replacing spaces with dashes
#
# blacklisted:          if present, project will not be built
# builddep:             override the package name to 'apt-get builddep', or should be false to skip if the project isn't packaged for Ubuntu
# install:              list of additional packages to 'apt-get install'
# repo-url:             git repo URL, if different to that linked in Users.md
# commit:               git branch, tag, or commit-id, otherwise HEAD is used
# extra-commands:       extra commands to execute before build
# sourcedir:            source directory containing meson.build, if not root of checkout
# config:               project configuration options to be passed to meson
# build:                targets to build (default: all install), or false to skip
#

2048.cpp:
  builddep: false

akira:
  builddep: false
  install:
  - libgranite-dev
  - libgtk-3-dev
  - valac
  blacklisted: 'needs libgranite >= 5.2.0, not in bionic'

aravis:
  builddep: false
  install:
  - gobject-introspection
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgtk-3-dev
  - libnotify-dev
  - libusb-1.0-0-dev
  - libxml2-dev

arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

bolt:
  builddep: false
  install:
  - libglib2.0-dev
  - libudev-dev
  - udev
  - libpolkit-gobject-1-dev
  - systemd
  - libsystemd-dev
  # pin at a working commit to avoid unstream borkage
  commit: 95388c0845340564c8c517b86134eede3bd880ba

budgie-desktop:
  builddep: false
  install:
  - valac
  - libgtk-3-dev
  - libwnck-3-dev
  - libpeas-dev
  - uuid-dev
  - libibus-1.0-dev
  - libgnome-desktop-3-dev
  - libaccountsservice-dev
  - intltool
  - libpulse-dev
  - sassc
  - libpolkit-agent-1-dev
  - libmutter-2-dev
  - libgnome-menu-3-dev
  - libupower-glib-dev
  - libgnome-bluetooth-dev
  - gtk-doc-tools
  - gnome-settings-daemon-dev
  - libasound2-dev
  build: false
  # pin at commit before libmutter >= 3 required, not in bionic
  commit: e1017252a61b47d26cbb391488edc1d3a366f5a0

cage:
  blacklisted: 'requires wlroots, not in bionic'

casync:
  install:
  - libudev-dev
  - udev

dav1d:
  builddep: false
  install:
  - nasm

dbus-broker:
  builddep: false
  install:
  - python-docutils
  - libdbus-1-dev
  - libglib2.0-dev
  - libsystemd-dev
  - systemd

dpdk:
  builddep: false
  repo-url: git://dpdk.org/dpdk
  build: false

dxvk:
  blacklisted: 'need to work out how to install vulcan devkit'

elementary-os:
  blacklisted: 'is a distribution'

emeus:
  builddep: false
  install:
  - gtk-doc-tools
  - libglib2.0-dev
  - libgtk-3-dev
  - libgirepository1.0-dev
  build: false

esp8266-arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

fedora-project:
  blacklisted: 'not a package'

feedreader:
  builddep: false
  install:
  - libcurl4-openssl-dev
  - libgdk-pixbuf2.0-dev
  - libgee-0.8-dev
  - libgoa-1.0-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgumbo-dev
  - libjson-glib-dev
  - libnotify-dev
  - libpeas-dev
  - libsecret-1-dev
  - libsqlite3-dev
  - libwebkit2gtk-4.0-dev
  - valac
  build: false

fractal:
  builddep: false
  repo-url: https://gitlab.gnome.org/World/fractal.git
  install:
  - cargo
  - gettext
  - libatk1.0-dev
  - libcariro2-dev
  - libdbus-1-dev
  - libgdk-pixbuf2.0-dev
  - libgspell-1-dev
  - libgtk-3-dev
  - libpango1.0-dev
  - libssl-dev
  - rustc
  blacklisted: 'requires gspell >= 1.8; just wraps cargo-build'

frida:
  blacklisted: 'repo-url is for frida-core, make a meson.build of frida using subprojects'

fwupd:
  install:
  - gnu-efi
  - libjson-glib-dev
  - help2man
  - valac
  # pin at a working commit before efiboot required, not packaged in bionic
  commit: cff980cfda882939b5a3a5c2baadb657d5dbb051

gamemode:
  builddep: false
  install:
  - libdbus-1-dev
  - libsystemd-dev
  - systemd

geary:
  install:
  - itstool
  - libfolks-dev
  - libgoa-1.0-dev
  - libjson-glib-dev
  - libunwind-dev
  repo-url: https://git.gnome.org/browse/geary
  # pin at commit before libhandy required, not packaged in bionic
  commit: a83a68ef3973b3630d1a8dd13b6b7a951378e593

glib:
  builddep: glib2.0
  build: false

gnome-boxes:
  install:
  - libwebkit2gtk-4.0-dev
  - freerdp2-dev
  # pin at commit before libvirt-gconfig 2.0 required, not packaged in bionic
  commit: v3.31.1

gnome-builder:
  # pin before libdazzle >= 3.29 required, not in bionic
  commit: 3.28.3
  # spellcheck uses enchant2, not in bionic
  config: -Dwith_spellcheck=false
  build: false

gnome-mpv:
  # pin before mpv >= 1.101 required, not in bionic
  commit: 47de9c9588651486fac8499ef849ee7375ebe2e6

gnome-recipes:
  install:
  - libgoa-1.0-dev
  - libjson-glib-dev

gnome-software:
  # pin before flatpak >= 0.99.3 required, not in bionic
  commit: 12031b42109892e50b38f4037b923335fdfb0fd0

gnome-twitch:
  build: false

gnome-usage:
  builddep: false
  install:
  - libaccountsservice-dev
  - libgtk-3-dev
  - libgtop2-dev
  - valac
  # pin before libdazzle required, not in bionic
  commit: 4272da4d89f3baccf821805fce72e2098579e9db

gnu-fribidi:
  builddep: fribidi
  # requires c2man
  config: -Ddocs=false

graphene:
  repo-url: git://github.com/ebassi/graphene

grilo:

grilo-plugins:
  # pin at commit before grilo >= 0.3.6 required, not in bionic
  commit: 770b11088c1b99ec979015faf95078c1e0dfe69e

gstreamer:
  builddep: gstreamer1.0
  # install fails in non-UTF8 locale due to encoding issue in gtkdochelper.py
  build: all

gtk+:
  builddep: libgtk-3-dev
  # pin at commit before pango >= 1.14.0 required, not in bionic
  commit: 894a0c0f
  build: false

gtkdapp:
  builddep: false
  install:
  - libgtkd-3-dev
  - gdc
  - gsettings-desktop-schemas-dev
  - libglib2.0-dev
  - gettext
  build: false

gvfs:
  install:
  - libbluray-dev
  - libnfs-dev
  # pin at commit before polkit-gobject-1 >= 0.114 required, not in bionic
  commit: 3a7bb06be72fc62b4ec524afe67febf0f529066d

hardcode-tray:
  builddep: false
  install:
  - libgirepository1.0-dev
  - libgtk-3-dev

helenos:
  blacklisted: 'no idea how to build this!'

hexchat:
  install:
  - libluajit-5.1-dev
  - python3-cffi

igt:
  builddep: intel-gpu-tools
  install:
  - libssl-dev
  - libdw-dev
  # pin at a commit which builds, since master is broken
  commit: 0dc1d6e4d4305a62c64242ec65709e44f5036cf4

ish:
  builddep: false
  install:
  - clang
  - libsqlite3-dev
  - lld
  # only builds with clang
  extra-commands: apt-get purge -y gcc
  build: false

janet:
  builddep: false

json:
  builddep: false

jsoncpp:
  builddep: false

kiwix-libraries:
  builddep: false
  install:
  - libicu-dev
  - libzim-dev
  blacklisted: 'needs libzim >= 4.0.0, not in bionic'

knot-resolver:
  blacklisted: 'needs libknot >= 2.8, not in bionic'

lc0:
  builddep: false
  install:
  - libopenblas-dev
  # tweak so we don't need python2 as well
  extra-commands: sed -i s!python!python3! checkdir.py

libcamera:
  builddep: false
  # http URL only supports dumb http transport which doesn't support shallow clone
  repo-url: git://linuxtv.org/libcamera.git
  install:
  - libudev-dev
  - python3-yaml

libdrm:

libepoxy:
  build: false

libfuse:
  install:
  - udev
  builddep: fuse

libgit2-glib:
  install:
  - python-gi-dev
  # workaround https://gitlab.gnome.org/GNOME/libgit2-glib/issues/5
  extra-commands: mkdir -p /usr/local/share/vala/vapi

libhttpseverywhere:
  builddep: false
  install:
  - valac
  - libjson-glib-dev
  - libsoup2.4-dev
  - libgee-0.8-dev
  - libarchive-dev
  - gobject-introspection
  build: false

libmodulemd:
  builddep: false
  install:
  - clang-format
  - gobject-introspection
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libglib2.0-doc
  - libmagic-dev
  - librpm-dev
  - libyaml-dev
  - libzstd-dev
  - pycodestyle
  - python-autopep8
  - valgrind
  # workaround assumption in #! line that /usr/bin/sh exists
  # workaround some zaniness
  # install black python formatted, not packaged in bionic
  extra-commands: sed -i s!usr/bin/sh!bin/sh! spec_tmpl.sh ; touch /usr/share/gtk-doc/html/glib/index.html ; touch /usr/share/gtk-doc/html/gobject/index.html ; pip3 install black

libosmscout:
  builddep: false

libspng:
  builddep: false
  install:
  - zlib1g-dev
  - libpng-dev

libui:
  builddep: false
  install:
  - libgtk-3-dev
  # workaround fallout from meson#5348
  extra-commands: sed -i s!cpp_eh=sc!cpp_eh=default! meson.build

libzim:
  builddep: zimlib

lightdm-webkit2-greeter:
  builddep: false
  commit: stable
  install:
  - libdbus-glib-1-dev
  - liblightdm-gobject-1-dev
  - libgtk-3-dev
  - libwebkit2gtk-4.0-dev
  repo-url: https://github.com/Antergos/lightdm-webkit2-greeter

marker:
  builddep: false
  install:
  - libglib2.0-dev
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libgtkspell3-3-dev
  - libwebkit2gtk-4.0-dev
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive
  # install generates so much output travis terminates job as log is too long
  build: all

mesa:
  install:
  - libegl1-mesa-dev
  - libxvmc-dev
  - python
  - python-mako
  # pin at commit before wayland needs to provide wayland-egl-backend (>= 1.15?), not in bionic
  commit: cb03803253b026d5f4c1e0fef431a12df461e6d8
  build: false

miraclecast:
  builddep: false
  install:
  - libreadline-dev
  - libudev-dev
  - libglib2.0-dev
  - libsystemd-dev
  build: false

mrsh:
  builddep: false

nautilus:
  install:
  - libgexiv2-dev
  - libseccomp-dev
  - libgstreamer-plugins-base1.0-dev
  repo-url: https://gitlab.gnome.org/GNOME/nautilus.git
  # pin at commit before glib >= 2.58.1 required, not in bionic
  commit: de17081f

nemo:
  install:
  - libxapp-dev
  # pin at commit before xapp >= 1.4.0 required, not in bionic
  commit: 80672f071742453ec0e84e4a46ec1ab28fe62379

oomd:
  builddep: false
  install:
  - libjsoncpp-dev
  # pin at commit before gcc-8 required
  commit: 05049df5a931411c996c53b048b3e054315481e1

openh264:
  builddep: false
  install:
  - nasm

openhmd:
  builddep: false
  install:
  - libhidapi-dev

orc:

ots:
  install:
  - libfreetype6-dev
  # workaround for meson issue #5070
  # uses submodules, but not as subprojects
  extra-commands: sed -i s#appleframeworks## meson.build ; git submodule update --init

outlier:
  builddep: false

pacman:
  repo-url: git://git.archlinux.org/pacman.git
  install:
  - libarchive-dev
  - libssl-dev

pango:
  install:
  - libfribidi-dev
  - libmount-dev
  builddep: pango1.0
  # pin at commit before harfbuzz >= 2.0.0 required, not in bionic
  commit: 546f4c242d6f4fe312de3b7c918a848e5172e18d

parzip:
  builddep: false
  install:
  - zlib1g-dev
  # later versions require C++ std::filesystem, which requires g++ >= 8, not in bionic
  commit: 1.3.0

peek:
  builddep: false
  install:
  - gettext
  - libgtk-3-dev
  - valac

picolibc:
  builddep: false
  extra-commands: mkdir _build ; cd _build ; ../do-native-configure ; cd ..
  config: -v

pipewire:
  builddep: false
  install:
  - libasound2-dev
  - libbluetooth-dev
  - libdbus-1-dev
  - libglib2.0-dev
  - libgstreamer1.0-dev
  - libgstreamer-plugins-base1.0-dev
  - libjack-dev
  - libpulse-dev
  - libsbc-dev
  - libudev-dev
  - libv4l-dev
  - libvulkan-dev
  repo-url: https://github.com/PipeWire/pipewire.git
  # jack in bionic is too old
  config: -Dpipewire-jack=false -Djack=false

pithos:
  install:
  - libglib2.0-dev

pitivi:
  blacklisted: 'has unpackaged subproject gst-transcoder, which depends on gstreamer-1.0 > 1.15.0, not in bionic'

playerctl:
  builddep: false
  install:
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev

polari:
  # pin at commit before gjs-1.0 1.53.90 required, not in bionic
  commit: c97477b23361855e22619546a297d7513163bb76

radare2:
  # pin at a commit which builds, since master is broken
  commit: 336c0e84fc53407b9a2ff2dcd97d7d59392fb0f0

rxdock:
  builddep: false
  build: false

sshfs:
  # pin at commit before libfuse3 required, not in bionic
  commit: 6cc86fc0bdaaeacfb1bd5e4336f2a2d1e5b189b8

sway:
  builddep: false
  install:
  - libjson-c-dev
  blacklisted: 'needs libjson-c-dev >= 0.13, not in bionic'

sysprof:
  install:
  - systemd
  - policykit-1
  # pin before libdazzle >= 3.30.0 required, not in bionic
  # pin at commit which build on 32-bit
  commit: 46d3c553e5e9314aaab3cd49673d8344324d2f0a

systemd:
  # workaround for meson#5113 systemd#12232
  extra-commands: sed -i s!.-Wl,--undefined.!! meson.build

szl:
  builddep: false
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init

taisei-project:
  builddep: false
  install:
  - libfreetype6-dev
  - libsdl2-dev
  - libsdl2-image-dev
  - libsdl2-mixer-dev
  - libpng-dev
  - libwebp-dev
  - python-docutils
  repo-url: https://github.com/taisei-project/taisei.git
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init

terminology:
  blacklisted: 'needs edje >=1.20.0, not in bionic'

tilix:
  install:
  - dub
  blacklisted: 'needs some D voodoo to let gtk D bindings dependency be found'

valum:
  builddep: false
  install:
  - valac
  - libsoup2.4-dev
  - libssl-dev
  # pin vsgi to workaround vsgi#3
  extra-commands: sed -i s!master!4c0318d3a2a7f47158ae220cae07c72af469d2e1! subprojects/vsgi.wrap

weston:
  blacklisted: 'needs wayland-protocols >= 1.13, not in bionic'

wlroots:
  builddep: false
  install:
  - libegl1-mesa-dev
  - libgbm-dev
  - libgles2-mesa-dev
  - libinput-dev
  - libpixman-1-dev
  - libwayland-dev
  - libxcb-composite0-dev
  - libxcb-image0-dev
  - libxkbcommon-dev
  - wayland-protocols
  # pin at commit before wayland-protocols >= 1.14 required, not in bionic
  commit: f1fcc685b62d5c37c3b99ce6bfeb11ac1fa59ea6

wxformbuilder:
  builddep: false
  install:
  - libwxgtk3.0-dev
  - libwxgtk-media3.0-dev

xi-gtk:
  builddep: false
  install:
  - valac
  - libgtk-3-dev
  - libjson-glib-dev

xorg:
  builddep: xorg-server

zathura:
  blacklisted: 'needs girara-gtk3 >= 0.3.2, not in bionic'

zstandard:
  builddep: zstd
  repo-url: https://github.com/facebook/zstd.git
  sourcedir: contrib/meson
  commit: v1.3.4
