#
# configuration for meson-corpus-test-update
#
# This file provides extra information for the list of projects taken from
# Users.md
#
# project names are converted to putative package names by lowercasing, and
# replacing spaces with dashes
#
# blacklisted:          if present, project will not be built
# builddep:             override the package name to 'apt-get builddep', or should be false to skip if the project isn't packaged for Ubuntu
# install:              list of additional packages to 'apt-get install'
# repo-url:             git repo URL, if different to that linked in Users.md
# commit:               git branch, tag, or commit-id, otherwise most recent tag is used, or master if no tags exist
# extra-commands:       extra commands to execute before build
# sourcedir:            source directory containing meson.build, if not root of checkout
# config:               project configuration options to be passed to meson
# build:                targets to build (default: all install), or false to skip
#

2048.cpp:
  builddep: false

akira:
  builddep: false
  install:
  - appstream-util
  - desktop-file-utils
  - gettext
  - libarchive-dev
  - libgoocanvas-2.0-dev
  - libgranite-dev
  - libgtk-3-dev
  - libjson-glib-dev
  - libxml2-dev
  - valac
  commit: v0.0.13

arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

budgie-desktop:
  commit: v10.5.2

cage:
  builddep: false
  install:
  - libwlroots-dev
  # commit before wlroots >= 0.11.0 required, not in focal
  commit: 79992f39f3f451cac8140bc1053f57e2355c4f3c

canfigger:
  builddep: false

chicken-libraries:
  blacklisted: 'this is an organization providing a collection of repos'

cozy:
  builddep: false
  install:
  - gettext
  - libglib2.0-dev
  - python3-distro
  - python3-gi
  - python3-mutagen
  - python3-peewee
  commit: 0.7.5

dav1d:
  builddep: false
  install:
  - nasm

dbus-broker:
  builddep: false
  install:
  - libdbus-1-dev
  - libglib2.0-dev
  - libsystemd-dev
  - python-docutils
  - systemd

dosbox-staging:
  builddep: false
  install:
  - libasound2-dev
  - libfluidsynth-dev
  - libopusfile-dev
  - libpng-dev
  - libsdl2-dev
  - libsdl2-net-dev

dpdk:
  repo-url: git://dpdk.org/dpdk
  install:
  - python3-pyelftools

dxvk:
  install:
  - gcc-mingw-w64-x86-64
  - g++-mingw-w64-x86-64
  config: --cross-file build-win64.txt
  extra-commands: update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix ; update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
  # master FTBFS
  commit: v1.7.2

elementary-os:
  blacklisted: 'is a distribution'

emeus:
  builddep: false
  install:
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libgtk-3-dev

entangle:
  repo-url: https://gitlab.com/entangle/entangle.git
  install:
  - appstream

esp8266-arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

fedora-project:
  blacklisted: 'not a package'

flecs:
  builddep: false
  commit: v2.3.2

foliate:
  builddep: false
  install:
  - appstream
  - gettext
  - gjs
  - libglib2.0-dev-bin

fractal:
  repo-url: https://gitlab.gnome.org/World/fractal.git
  builddep: false
  # tag before libhandy1 required, not in focal
  commit: 4.4.0
  install:
  - appstream
  - cargo
  - gettext
  - libatk1.0-dev
  - libcairo2-dev
  - libdbus-1-dev
  - libgdk-pixbuf2.0-dev
  - libges-1.0-dev
  - libgspell-1-dev
  - libgstreamer-plugins-bad1.0-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgtk-3-dev
  - libgtksourceview-4-dev
  - libhandy-0.0-dev
  - libpango1.0-dev
  - libssl-dev
  - rustc

frida:
  blacklisted: 'repo-url is for frida-core, make a meson.build of frida using subprojects'

fwupd:
  install:
  - libsystemd-dev
  - libcurl4-openssl-dev

geary:
  repo-url: https://git.gnome.org/browse/geary
  install:
  - libgsound-dev
  commit: 3.36.3.1

glib:
  builddep: glib2.0

glorytun:
  builddep: false
  install:
  - libsodium-dev
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

gnome-boxes:
  install:
  - libhandy-0.0-dev
  - libgtksourceview-4-dev
  commit: v3.38.0

gnome-builder:
  # update_manager requires libportal, not packaged
  # custom clang11 install in GitHub runner image is missing the equivalent of libclang-11-dev
  config: -Dplugin_update_manager=false -Dplugin_clang=false
  # tag before libdazzle-1.0 >= 3.37.0 required, not in focal
  commit: 3.36.0
  extra-commands: sed -i s!libide_lsp_sources,!libide_lsp_sources,libide_lsp_generated_headers,! src/libide/lsp/meson.build

gnome-mpv:
  repo-url: https://github.com/celluloid-player/celluloid.git

gnome-software:
  # requires libmalcontent, not packaged
  config: -Dmalcontent=false
  install:
  - libcurl4-openssl-dev
  - libgirepository1.0-dev
  - liblmdb-dev
  - libstemmer-dev
  - gperf
  - libpam-dev

gnome-usage:
  install:
  - libgirepository1.0-dev
  - libtracker-sparql-2.0-dev
  commit: v3.37.1

gnu-fribidi:
  builddep: fribidi
  # requires c2man
  config: -Ddocs=false

graphene:
  repo-url: git://github.com/ebassi/graphene

gstreamer:
  builddep: gstreamer1.0

gtk+:
  builddep: gtk+3.0
  install:
  - libgstreamer-plugins-bad1.0-dev
  - libgraphene-1.0-dev
  - libvulkan-dev
  extra-commands: sed -i s!master!main! subprojects/glib.wrap

gtkdapp:
  builddep: false
  install:
  - gdc
  - gsettings-desktop-schemas-dev
  - libgtk-3-dev
  - libgtkd-3-dev
  - librsvg2-dev
  # need to work out how it's possible to build this
  build: false

gvfs:
  # tag before polkit >= 0.114 required, not in focal
  commit: 1.37.1

hardcode-tray:
  builddep: false
  install:
  - libgirepository1.0-dev
  - libgtk-3-dev

hexchat:
  install:
  - libluajit-5.1-dev
  - python3-cffi

helenos:
  blacklisted: 'no idea how to build this!'

igt:
  builddep: intel-gpu-tools
  install:
  - libasound2-dev

inih:
  builddep: false

ish:
  builddep: false
  # only builds with clang
  install:
  - clang
  - libsqlite3-dev
  - lld
  - python-is-python3

janet:
  commit: v1.8.1
  builddep: false

json:
  builddep: false

jsoncpp:
  builddep: false

kiwix-libraries:
  builddep: false
  install:
  - libcurl4-openssl-dev
  - libicu-dev
  - libkainjow-mustache-dev
  - libpugixml-dev
  - libzim-dev
  # tag before libzim >= 5.0.0 required, not in focal
  commit: 5.0.0
  extra-commands: ln -s /usr/include/kainjow/mustache.hpp /usr/include

knot-resolver:
  # commit before libknot >= 2.8 required, not in focal
  commit: 1bbe50b47cb41fd7459721fe08abea7cd2bf3888
  # uses submodules, but not as subprojects
  # include commit 4157d3c298cbc264a63a85341dcad701c48c0655 to patch .gitmodules for deleted repositories
  extra-commands: sed -i 's!https://github.com/cloudflare/!https://gitlab.labs.nic.cz/knot/3rdparty/!;s!https://github.com/telemachus/!https://gitlab.labs.nic.cz/knot/3rdparty/lua-!' .gitmodules ; git submodule update --init --recursive

ksh:
  commit: ksh2020

lc0:
  builddep: false
  install:
  - libopenblas-dev

le:
  # package 'le' in ubuntu is something different
  builddep: false
  install:
  - libgtk-3-dev
  - python3-pybind11
  # ftbs currently
  build: false

libcamera:
  # http URL only supports dumb http transport which doesn't support shallow clone
  repo-url: git://linuxtv.org/libcamera.git
  builddep: false
  install:
  - libboost-dev
  - gnutls-dev
  - python3-jinja2
  - python3-ply
  - python3-yaml

libeconf:
  builddep: false

libfuse:
  builddep: fuse
  config: -Duseroot=false
  install:
  - udev

libgit2-glib:
  # pin before version requiring glib 2.68, not in focal
  commit: 'v0.99.0.1'
  # don't install to work-around bogus DESTDIR handling in custom install script
  build: all

libhttpseverywhere:
  builddep: false
  install:
  - gobject-introspection
  - libarchive-dev
  - libgee-0.8-dev
  - libgirepository1.0-dev
  - libjson-glib-dev
  - libsoup2.4-dev
  - valac

libmodulemd:
  builddep: false
  install:
  - black
  - clang-format
  - gobject-introspection
  - gtk-doc-tools
  - help2man
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libglib2.0-doc
  - libmagic-dev
  - librpm-dev
  - libyaml-dev
  - libzstd-dev
  - pycodestyle
  - python3-autopep8
  - python3-gi
  - valgrind

libosmscout:
  builddep: false
  install:
  - libxml2-dev
  # cairo demo FTBFS
  config: -DenableMapCairo=false

libratbag:
  install:
  - valgrind

libspng:
  builddep: false

libui:
  builddep: false
  install:
  - libgtk-3-dev

libvirt:
  repo-url: https://libvirt.org/git/libvirt.git
  install:
  - libtirpc-dev

libzim:
  builddep: zimlib
  install:
  - libzstd-dev

marker:
  builddep: false
  install:
  - libglib2.0-dev-bin
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libwebkit2gtk-4.0-dev
  - libgtkspell3-3-dev
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive
  # build produces so much output the job exceeds the maximum log length
  build: false

mesa:
  # tag before libdrm_intel >=2.4.102 required, not in focal
  commit: 1f37662c093ee168d0669d0ea0c7f169e272d0c7

miraclecast:
  builddep: false
  install:
  - libglib2.0-dev
  - libreadline-dev
  - libsystemd-dev
  - libudev-dev

mrsh:
  builddep: false

nautilus:
  commit: 3.37.3

nemo:
  commit: 4.6.5

ocherbook:
  builddep: false

oomd:
  commit: v0.4.0

openh264:
  builddep: false
  install:
  - nasm

openhmd:
  builddep: false
  install:
  - libhidapi-dev

opentitan:
  builddep: false
  blacklisted: 'need to work out how to install /tools/riscv/ toolchain'

ots:
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

outlier:
  builddep: false

pacman:
  repo-url: git://git.archlinux.org/pacman.git
  install:
  - libarchive-dev
  - libssl-dev
  # pin FTBS
  commit: v5.2.2

pango:
  builddep: pango1.0

paper-rock-scissors:
  builddep: false
  install:
  - gdc

parzip:
  builddep: false

peek:
  install:
  - python-is-python3

picolibc:
  builddep: false
  # hack to invoke the script which configures this
  extra-commands: mkdir _build && cd _build && ../scripts/do-native-configure && cd ..
  config: -v

pipewire:
  install:
  - libbluetooth-dev
  - libjack-jackd2-dev
  - libvulkan-dev

pithos:
  install:
  - libglib2.0-dev

polari:
  commit: 3.38.0

qboot:
  builddep: false

qemu:
  repo-url: https://gitlab.com/qemu-project/qemu
  # hack to invoke the script which configures this
  extra-commands: mkdir _build && cd _build && ../configure && cd ..
  config: -v
  build: false

rizin:
  repo-url: https://github.com/rizinorg/rizin.git
  builddep: false

rmw:
  repo-url: https://github.com/theimpossibleastronaut/rmw.git
  builddep: false
  install:
  - gettext
  - libncurses-dev

rxdock:
  builddep: false
  # update libeigen wrap for new location (unfortunately the archive is different)
  # https://gitlab.com/rxdock/rxdock/-/merge_requests/2
  extra-commands: sed -i 's!http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2!https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2!;s!eigen-eigen-323c052e1731!eigen-3.3.7!;s!9f13cf90dedbe3e52a19f43000d71fdf72e986beb9a5436dddcd61ff9d77a3ce!685adf14bd8e9c015b78097c1dc22f2f01343756f196acdc76a678e1ae352e11!;s!/1/!/3/!;s!-1-!-3-!;s!3d8ffc134e8af95e5de6c5d4614971028d27bf5f01f3082179522d536750261b!233bc7daeaf93c0284a6ec32009aabe2f5e001fd377a8c090a644697d51f2d25!' subprojects/eigen.wrap

scrcpy:
  # fake scrcpy-server
  extra-commands: touch server/scrcpy-server
  config: -Dprebuilt_server=server/scrcpy-server

sequeler:
  builddep: false
  install:
  - gettext
  - libgda-5.0-dev
  - libgranite-dev
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libsecret-1-dev
  - libssh2-1-dev
  - libxml2-dev
  - valac

siril:
  install:
  - cmake
  - libexiv2-dev
  - libjson-glib-dev

sshfs:
  install:
  - libfuse3-dev

sysprof:
  commit: sysprof-3.36.0

systemd:
  install:
  - python3-jinja2

sway:
  # needs aligned wlroots to build, but subproject isn't in repository
  commit: '1.4'

szl:
  builddep: false
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

taisei-project:
  repo-url: https://github.com/taisei-project/taisei.git
  builddep: false
  install:
  - libgl-dev
  - libglx-dev
  - libx11-dev
  - libxext-dev
  - python-docutils
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive
  # master ftbs
  commit: 324dccb79ae0033a1613c4b994ac97c813e516a6

terminology:
  install:
  - libeet-bin

tilix:
  install:
  - appstream

tizonia:
  builddep: false
  install:
  - libboost-chrono-dev
  - libboost-filesystem-dev
  - libboost-program-options-dev
  - libboost-python-dev
  - libboost-thread-dev
  - libcurl4-gnutls-dev
  - libdbus-1-dev
  - libfaad-dev
  - libfishsound1-dev
  - libflac-dev
  - liblog4c-dev
  - libmad0-dev
  - libmediainfo-dev
  - libmp3lame-dev
  - libmpg123-dev
  - liboggz2-dev
  - libopus-dev
  - libopusfile-dev
  - libpulse-dev
  - libsdl1.2-dev
  - libsndfile1-dev
  - libsqlite3-dev
  - libtag1-dev
  - libvpx-dev
  - uuid-dev
  config: -Dlibspotify=false
  # build fails with "virtual memory exhausted"
  build: false

ufjf-mltk:
  builddep: false
  commit: 22112321ba7ed6052c2021a47b57a866fdae4f0c

vala-language-server:
  builddep: false
  install:
  - libgee-0.8-dev
  - libjsonrpc-glib-1.0-dev
  - libvala-dev
  - valac
  commit: '0.48'

valum:
  builddep: false
  install:
  - libsoup2.4-dev
  - libssl-dev
  - valac

venom:
  builddep: false
  install:
  - libcanberra-dev
  - libgee-0.8-dev
  - libgspell-1-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgtk-3-dev
  - libjson-glib-dev
  - libsoup2.4-dev
  - libsqlcipher-dev
  - libtoxcore-dev
  - valac
  # disable until https://github.com/naxuroqa/Venom/issues/497 is resolved
  blacklisted: 'not compatible with recent valac'

vmaf:
  builddep: false
  install:
  - nasm
  sourcedir: libvmaf

weston:
  install:
  - libpipewire-0.2-dev

wlroots:
  commit: 0.12.0

wxformbuilder:
  builddep: false
  install:
  - libwxgtk3.0-gtk3-dev
  - libwxgtk-media3.0-gtk3-dev
  # build produces so many warnings the job exceeds the maximum log length
  build: false

xi-gtk:
  builddep: false
  install:
  - libgtk-3-dev
  - libjson-glib-dev
  - valac

xorg:
  builddep: xorg-server

x-test-suite:
  builddep: false
  install:
  - libx11-dev
  - libxaw7-dev
  - libxext-dev
  - libxi-dev
  - libxmu-dev
  - libxtst-dev
  - x11-utils
  - x11-xserver-utils
  - xfonts-utils
  # xts requires a running X server to build!
  build: false

zathura:
  commit: 0.4.7

zrythm:
  repo-url: https://github.com/zrythm/zrythm.git
  builddep: false
  install:
  - cmake
  - gettext
  - guile-2.2-dev
  - help2man
  - libfftw3-dev
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libjack-jackd2-dev
  - librubberband-dev
  - libsamplerate0-dev
  - libsndfile1-dev
  - libyaml-dev
  - libzstd-dev
  - xdg-utils

zstandard:
  # url in Users.md links to specific commit
  repo-url: https://github.com/facebook/zstd.git
  builddep: zstd
  sourcedir: build/meson
