#
# configuration for meson-corpus-test-update
#
# This file provides extra information for the list of projects taken from
# Users.md
#
# project names are converted to putative package names by lowercasing, and
# replacing spaces with dashes
#
# blacklisted:          if present, project will not be built
# builddep:             override the package name to 'apt-get builddep', or should be false to skip if the project isn't packaged for Ubuntu
# install:              list of additional packages to 'apt-get install'
# repo-url:             git repo URL, if different to that linked in Users.md
# commit:               git branch, tag, or commit-id, otherwise HEAD is used
# extra-commands:       extra commands to execute before build
# sourcedir:            source directory containing meson.build, if not root of checkout
# config:               project configuration options to be passed to meson
# build:                targets to build (default: all install), or false to skip
#

2048.cpp:
  builddep: false

akira:
  builddep: false
  install:
  - appstream-util
  - desktop-file-utils
  - gettext
  - libarchive-dev
  - libgoocanvas-2.0-dev
  - libgranite-dev
  - libgtk-3-dev
  - libjson-glib-dev
  - libxml2-dev
  - valac

arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

cage:
  builddep: false
  install:
  - libwlroots-dev

cozy:
  builddep: false
  install:
  - libglib2.0-dev
  - python3-distro
  - python3-peewee
  - python3-mutagen

dav1d:
  builddep: false
  install:
  - nasm

dbus-broker:
  builddep: false
  install:
  - libdbus-1-dev
  - libglib2.0-dev
  - libsystemd-dev
  - python-docutils
  - systemd

dpdk:
  repo-url: git://dpdk.org/dpdk

dxvk:
  install:
  - gcc-mingw-w64-x86-64
  - g++-mingw-w64-x86-64
  config: --cross-file build-win64.txt
  extra-commands: update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix ; update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

elementary-os:
  blacklisted: 'is a distribution'

emeus:
  builddep: false
  install:
  - gtk-doc-tools
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libgtk-3-dev

esp8266-arduino-sample-project:
  blacklisted: 'need to work out how to setup cross-env'

fedora-project:
  blacklisted: 'not a package'

flecs:
  builddep: false

foliate:
  builddep: false
  install:
  - gettext
  - gjs
  - libglib2.0-dev-bin

fractal:
  repo-url: https://gitlab.gnome.org/World/fractal.git
  builddep: false
  install:
  - cargo
  - gettext
  - libatk1.0-dev
  - libcairo2-dev
  - libdbus-1-dev
  - libgdk-pixbuf2.0-dev
  - libges-1.0-dev
  - libgspell-1-dev
  - libgstreamer-plugins-bad1.0-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgtk-3-dev
  - libgtksourceview-4-dev
  - libhandy-0.0-dev
  - libpango1.0-dev
  - libssl-dev
  - rustc

frida:
  blacklisted: 'repo-url is for frida-core, make a meson.build of frida using subprojects'

geary:
  repo-url: https://git.gnome.org/browse/geary
  install:
  - libgsound-dev

glib:
  builddep: glib2.0

glorytun:
  builddep: false
  install:
  - libsodium-dev
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

gnome-boxes:
  install:
  - libhandy-0.0-dev

gnome-builder:
  # requires libportal, not packaged
  config: -Dplugin_update_manager=false
  # tag before libdazzle-1.0 >= 3.37.0 required, not in focal
  commit: 3.36.0
  extra-commands: sed -i s!libide_lsp_sources,!libide_lsp_sources,libide_lsp_generated_headers,! src/libide/lsp/meson.build

gnome-software:
  # requires libmalcontent, not packaged
  config: -Dmalcontent=false

gnome-usage:
  install:
  - libtracker-sparql-2.0-dev

gnu-fribidi:
  builddep: fribidi
  # requires c2man
  config: -Ddocs=false

graphene:
  repo-url: git://github.com/ebassi/graphene

gstreamer:
  builddep: gstreamer1.0

gtk+:
  builddep: gtk+3.0
  install:
  - libgstreamer-plugins-bad1.0-dev
  - libgraphene-1.0-dev

gtkdapp:
  builddep: false
  install:
  - gdc
  - gsettings-desktop-schemas-dev
  - libgtk-3-dev
  - libgtkd-3-dev
  - librsvg2-dev
  # need to work out how it's possible to build this
  build: false

gvfs:
  # tag before polkit >= 0.114 required, not in focal
  commit: 1.37.1

hardcode-tray:
  builddep: false
  install:
  - libgirepository1.0-dev
  - libgtk-3-dev

hexchat:
  install:
  - libluajit-5.1-dev
  - python3-cffi

helenos:
  blacklisted: 'no idea how to build this!'

igt:
  builddep: intel-gpu-tools

inih:
  builddep: false

ish:
  builddep: false
  # only builds with clang
  install:
  - clang
  - libsqlite3-dev
  - lld
  - python-is-python3

janet:
  builddep: false

json:
  builddep: false

jsoncpp:
  builddep: false

kiwix-libraries:
  builddep: false
  install:
  - libcurl4-openssl-dev
  - libicu-dev
  - libkainjow-mustache-dev
  - libpugixml-dev
  - libzim-dev
  # tag before libzim >= 5.0.0 required, not in focal
  commit: 5.0.0
  extra-commands: ln -s /usr/include/kainjow/mustache.hpp /usr/include

knot-resolver:
  # commit before libknot >= 2.8 required, not in focal
  commit: 1bbe50b47cb41fd7459721fe08abea7cd2bf3888
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

ksh:
  commit: ksh2020

lc0:
  builddep: false
  install:
  - libopenblas-dev

libcamera:
  # http URL only supports dumb http transport which doesn't support shallow clone
  repo-url: git://linuxtv.org/libcamera.git
  builddep: false
  install:
  - python3-yaml

libfuse:
  builddep: fuse
  install:
  - udev

libhttpseverywhere:
  builddep: false
  install:
  - gobject-introspection
  - libarchive-dev
  - libgee-0.8-dev
  - libgirepository1.0-dev
  - libjson-glib-dev
  - libsoup2.4-dev
  - valac

libmodulemd:
  builddep: false
  install:
  - black
  - clang-format
  - gobject-introspection
  - gtk-doc-tools
  - help2man
  - libgirepository1.0-dev
  - libglib2.0-dev
  - libglib2.0-doc
  - libmagic-dev
  - librpm-dev
  - libyaml-dev
  - libzstd-dev
  - pycodestyle
  - python3-autopep8
  - valgrind

libosmscout:
  builddep: false

libratbag:
  install:
  - valgrind
  blacklisted: 'https://github.com/mesonbuild/meson/issues/6845'

libspng:
  builddep: false

libui:
  builddep: false
  install:
  - libgtk-3-dev

libzim:
  builddep: zimlib

marker:
  builddep: false
  install:
  - libglib2.0-dev-bin
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libwebkit2gtk-4.0-dev
  - libgtkspell3-3-dev
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive
  # build produces so much output the job exceeds the maximum log length
  build: false

miraclecast:
  builddep: false
  install:
  - libglib2.0-dev
  - libreadline-dev
  - libsystemd-dev
  - libudev-dev

mrsh:
  builddep: false

ocherbook:
  builddep: false

openh264:
  builddep: false
  install:
  - nasm

openhmd:
  builddep: false
  install:
  - libhidapi-dev

opentitan:
  builddep: false
  blacklisted: 'need to work out how to install /tools/riscv/ toolchain'

ots:
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

outlier:
  builddep: false

pacman:
  repo-url: git://git.archlinux.org/pacman.git
  install:
  - libarchive-dev
  - libssl-dev

pango:
  builddep: pango1.0

parzip:
  builddep: false

picolibc:
  builddep: false
  # hack to invoke the script which configures this
  extra-commands: mkdir _build ; cd _build ; ../do-native-configure ; cd ..
  config: -v

pipewire:
  install:
  - libbluetooth-dev
  - libjack-jackd2-dev
  - libvulkan-dev

pithos:
  install:
  - libglib2.0-dev

qboot:
  builddep: false

rxdock:
  builddep: false

scrcpy:
  # fake scrcpy-server
  extra-commands: touch server/scrcpy-server
  config: -Dprebuilt_server=server/scrcpy-server

sequeler:
  builddep: false
  install:
  - gettext
  - libgda-5.0-dev
  - libgranite-dev
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libsecret-1-dev
  - libssh2-1-dev
  - libxml2-dev
  - valac

sshfs:
  install:
  - libfuse3-dev

sway:
  # needs aligned wlroots to build, but subproject isn't in repository
  build: false

szl:
  builddep: false
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

taisei-project:
  repo-url: https://github.com/taisei-project/taisei.git
  builddep: false
  install:
  - libgl-dev
  - libglx-dev
  - libx11-dev
  - libxext-dev
  - python-docutils
  # uses submodules, but not as subprojects
  extra-commands: git submodule update --init --recursive

tizonia:
  builddep: false
  install:
  - libboost-chrono-dev
  - libboost-filesystem-dev
  - libboost-program-options-dev
  - libboost-python-dev
  - libboost-thread-dev
  - liblog4c-dev
  - uuid-dev
  blacklisted: 'https://github.com/mesonbuild/meson/issues/6844'

valum:
  builddep: false
  install:
  - libsoup2.4-dev
  - libssl-dev
  - valac

venom:
  builddep: false
  install:
  - libcanberra-dev
  - libgee-0.8-dev
  - libgspell-1-dev
  - libgstreamer-plugins-base1.0-dev
  - libgstreamer1.0-dev
  - libgtk-3-dev
  - libjson-glib-dev
  - libsoup2.4-dev
  - libsqlcipher-dev
  - libtoxcore-dev
  - valac
  # disable until https://github.com/naxuroqa/Venom/issues/497 is resolved
  blacklisted: 'not compatible with recent valac'

vmaf:
  builddep: false
  sourcedir: libvmaf

weston:
  install:
  - libpipewire-0.2-dev

wxformbuilder:
  builddep: false
  install:
  - libwxgtk3.0-gtk3-dev
  - libwxgtk-media3.0-gtk3-dev
  # build produces so many warnings the job exceeds the maximum log length
  build: false

xi-gtk:
  builddep: false
  install:
  - libgtk-3-dev
  - libjson-glib-dev
  - valac

xorg:
  builddep: xorg-server

zrythm:
  # zrythm.org only supports dumb http transport, which doesn't support shallow clones
  repo-url: https://github.com/zrythm/zrythm.git
  builddep: false
  install:
  - gettext
  - libfftw3-dev
  - libgtk-3-dev
  - libjack-jackd2-dev
  - librubberband-dev
  - libsamplerate0-dev
  - libsndfile1-dev
  - libyaml-dev
  - xdg-utils

zstandard:
  # url in Users.md links to specific commit
  repo-url: https://github.com/facebook/zstd.git
  builddep: zstd
  sourcedir: build/meson
