FROM ubuntu:artful

RUN sed -i '/^#\sdeb-src /s/^#\s//' /etc/apt/sources.list \
&& apt-get -y update \
&& apt-get -y upgrade \
&& apt-get -y build-dep ${builddep} \
&& apt-get -y install ${alsoinstall} \
&& apt-get -y install ninja-build python3-pip git
